"""add models marca and tipo

Revision ID: 093f7850977c
Revises: caf9b023b4d8
Create Date: 2024-06-18 23:04:56.089309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093f7850977c'
down_revision = 'caf9b023b4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo')
    op.drop_table('marca')
    # ### end Alembic commands ###
