"""add foreign key

Revision ID: 63c7c38dc2c6
Revises: 06a97b8bf720
Create Date: 2024-06-25 20:15:05.238683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c7c38dc2c6'
down_revision = '06a97b8bf720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('marca_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'marca', ['marca_id'], ['id'])
        batch_op.create_foreign_key(None, 'tipo', ['tipo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('marca_id')
        batch_op.drop_column('tipo_id')

    # ### end Alembic commands ###
